### ISSUE TITLE
How deploy spring-petclinic-cloud to k8s without wavefront ?

### ISSUE THREAD

**Issue by patsevanton** [wavefrontHQ/wavefront-spring-boot#127]
Hello! Sorry that i create issue. But i dont know where i can ask.
I use project https://github.com/spring-petclinic/spring-petclinic-cloud
But project spring-petclinic-cloud use wavefront.
I can not disable wavefront.
I create issue https://github.com/spring-petclinic/spring-petclinic-cloud/issues/39 - have full config and logs.
I try disable wavefront with code:
```
---
spring:
  profiles: kubernetes
  cloud:
    config:
      enabled: false
    kubernetes:
      reload:
        strategy: restart-context
        enabled: true
      config:
        enabled: true
        name: petclinic-config
management:
  endpoint:
    restart:
      enabled: true
  metrics:
    export:
      wavefront:
        enabled: false
```

Please help. Where i can investigate this issue?
Thanks a lot!
