### ISSUE TITLE
Use Wavefront proxy for URI when running on Tanzu Application Service

### ISSUE THREAD

**Issue by odedia** [wavefrontHQ/wavefront-spring-boot#52]
Tanzu Application Service has a tile for the Wavefront Proxy.

TAS developers are used to the idea of auto-configuring their Spring Boot application when a proper service binding exists (such as RabbitMQ or MySQL).

It would be a pleasant experience to have auto-configuration of the Wavefront proxy URI when a developer binds the Wavefront proxy to their application in TAS. 
Today, developers can only dynamically get the value from the wavefront proxy if they use a Config server, because properties in `manifest.yml` cannot accept environment variables such as `${vcap.services...}` which are injected to the container at a later stage.

Here's a possible code block that uses [cfenv](https://github.com/pivotal-cf/java-cfenv) to find the information.

```
try {
	CfEnv cfEnv = new CfEnv();
	CfCredentials creds = cfEnv.findCredentialsByLabel("wavefront-proxy");
	String uri = creds.getHost().concat(":").concat(creds.getPort());
	// Set the wavefront URI = uri
	// Optional - remove/ignore a provided wavefront token if exists, since we should use the token set in the proxy in that case.
	
} catch (IllegalArgumentException e) {
	//Continue normal flow
}
```

**Comment by snicoll** [comment]
Thanks for the suggestion.

> Today, developers can only dynamically get the value from the wavefront proxy if they use a Config server, because properties in manifest.yml cannot accept environment variables such as ${vcap.services...} which are injected to the container at a later stage.

I don't understand what you meant by that.

> Here's a possible code block that uses cfenv to find the information.

Can you share a `vcap` output where the proxy is configured? Looking for `wavefront-proxy` in any key sounds like a bit dangerous so I'd like to make sure I understood what you mean.

**Comment by odedia** [comment]
Here's an output of a `cf env` for an application that is bound to the wavefront-proxy:
```
{
  "staging_env_json": {},
  "running_env_json": {},
  "system_env_json": {
    "VCAP_SERVICES": {
      "wavefront-proxy": [
        {
          "label": "wavefront-proxy",
          "provider": null,
          "plan": "standard",
          "name": "remove",
          "tags": [
            "wavefront",
            "metrics"
          ],
          "instance_name": "remove",
          "binding_name": null,
          "credentials": {
            "hostname": "192.168.8.10",
            "port": 2878,
            "distributionPort": 2878,
            "tracingPort": 30000
          },
          "syslog_drain_url": null,
          "volume_mounts": []
        }
      ]
    }
  },
  "application_env_json": {
    "VCAP_APPLICATION": {
      ...
    }
  }
}
```

The `label` is set by the vendor while the `name` is set by the Operator, that's why I think it's safer to use the label which should be the same across environments. Since there's a tag called `wavefront`, It's also possible to use `cfEnv.findCredentialsByTag('wavefront')`.

Regarding the `manifest.yml`: When I have a Config server, I can provide the following in my `application.yml` because the application will only fetch the properties on startup after `vcap` env variables were injected (I named by service instance `wavefront` in this example):

```
management:
  metrics:
    export:
      wavefront:
        uri: ${vcap.services.wavefront.credentials.hostname}:${vcap.services.wavefront.credentials.port}
```

I can't do the same in a `manifest.yml` because it cannot accept environment variables as values. For example the bold part below will not work:
```
---
applications:
  - name: my-service
    path: target/app.jar
    buildpacks:
      - java_buildpack_offline
    health-check-type: http
    health-check-http-endpoint: /actuator/health
    env:
      JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ } }'
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
      MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: **${vcap.services.wavefront.credentials.hostname}:${vcap.services.wavefront.credentials.port}**
```

It's possible to hard-code the value but this would mean that any change to the host of the proxy would require to edit all manifests for all deployed applications.

Thanks.
